#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of Trie-Grid.
# 
# Trie-Grid is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Trie-Grid is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Trie-Grid.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T empty
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L empty.old <(echo \
'$ test -x ./trie
$ print() { printf '\''%s\n'\'' "$@"; }
$ trie() { ./trie >/dev/null; }
$ echo -n|trie
$ print|trie
trie: error: line #1: tries cannot contain empty keys
command failed: print|trie
$ print $'\''\x0'\''|trie
trie: error: line #1: tries cannot contain empty keys
command failed: print $'\''\x0'\''|trie
$ print '\'''\''|trie
trie: error: line #1: tries cannot contain empty keys
command failed: print '\'''\''|trie
$ print a '\'''\''|trie
trie: error: line #2: tries cannot contain empty keys
command failed: print a '\'''\''|trie
$ print a b '\'''\''|trie
trie: error: line #3: tries cannot contain empty keys
command failed: print a b '\'''\''|trie'
) -L empty.new <(
echo '$ test -x ./trie'
test -x ./trie 2>&1 ||
echo 'command failed: test -x ./trie'

echo '$ print() { printf '\''%s\n'\'' "$@"; }'
print() { printf '%s\n' "$@"; } 2>&1 ||
echo 'command failed: print() { printf '\''%s\n'\'' "$@"; }'

echo '$ trie() { ./trie >/dev/null; }'
trie() { ./trie >/dev/null; } 2>&1 ||
echo 'command failed: trie() { ./trie >/dev/null; }'

echo '$ echo -n|trie'
echo -n|trie 2>&1 ||
echo 'command failed: echo -n|trie'

echo '$ print|trie'
print|trie 2>&1 ||
echo 'command failed: print|trie'

echo '$ print $'\''\x0'\''|trie'
print $'\x0'|trie 2>&1 ||
echo 'command failed: print $'\''\x0'\''|trie'

echo '$ print '\'''\''|trie'
print ''|trie 2>&1 ||
echo 'command failed: print '\'''\''|trie'

echo '$ print a '\'''\''|trie'
print a ''|trie 2>&1 ||
echo 'command failed: print a '\'''\''|trie'

echo '$ print a b '\'''\''|trie'
print a b ''|trie 2>&1 ||
echo 'command failed: print a b '\'''\''|trie'
)

