#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of Trie-Grid.
# 
# Trie-Grid is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Trie-Grid is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Trie-Grid.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T sort-only
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L sort-only.old <(echo \
'$ test -x ./trie
$ print() { printf '\''%s\n'\'' "$@"; }
$ trie() { ./trie -S -q; }
$ print b a|trie
a
b
$ print a a b|trie
a
a
b
$ print a b a|trie
a
a
b
$ print a b b|trie
a
b
b
$ print b b a|trie
a
b
b
$ print a A|trie
A
a
$ prints() { python -c $'\''\nfrom sys import argv\nfrom sys import stdout\nfrom re import sub\nu = lambda s: sub(r"\\\\x([0-9a-f]{1,2})", lambda m: "%c" % int(m.group(1), 16), s)\nfor a in argv[1:]:\n\tstdout.write(u(a))\n\tstdout.write("\\n")\n'\'' "$@"; }
$ prints a '\''\x0'\'' '\''\xff'\''|trie
\x0
a
\xff
$ prints xay '\''x\x0y'\'' '\''x\xffy'\''|trie
x\x0y
xay
x\xffy'
) -L sort-only.new <(
echo '$ test -x ./trie'
test -x ./trie 2>&1 ||
echo 'command failed: test -x ./trie'

echo '$ print() { printf '\''%s\n'\'' "$@"; }'
print() { printf '%s\n' "$@"; } 2>&1 ||
echo 'command failed: print() { printf '\''%s\n'\'' "$@"; }'

echo '$ trie() { ./trie -S -q; }'
trie() { ./trie -S -q; } 2>&1 ||
echo 'command failed: trie() { ./trie -S -q; }'

echo '$ print b a|trie'
print b a|trie 2>&1 ||
echo 'command failed: print b a|trie'

echo '$ print a a b|trie'
print a a b|trie 2>&1 ||
echo 'command failed: print a a b|trie'

echo '$ print a b a|trie'
print a b a|trie 2>&1 ||
echo 'command failed: print a b a|trie'

echo '$ print a b b|trie'
print a b b|trie 2>&1 ||
echo 'command failed: print a b b|trie'

echo '$ print b b a|trie'
print b b a|trie 2>&1 ||
echo 'command failed: print b b a|trie'

echo '$ print a A|trie'
print a A|trie 2>&1 ||
echo 'command failed: print a A|trie'

echo '$ prints() { python -c $'\''\nfrom sys import argv\nfrom sys import stdout\nfrom re import sub\nu = lambda s: sub(r"\\\\x([0-9a-f]{1,2})", lambda m: "%c" % int(m.group(1), 16), s)\nfor a in argv[1:]:\n\tstdout.write(u(a))\n\tstdout.write("\\n")\n'\'' "$@"; }'
prints() { python -c $'\nfrom sys import argv\nfrom sys import stdout\nfrom re import sub\nu = lambda s: sub(r"\\\\x([0-9a-f]{1,2})", lambda m: "%c" % int(m.group(1), 16), s)\nfor a in argv[1:]:\n\tstdout.write(u(a))\n\tstdout.write("\\n")\n' "$@"; } 2>&1 ||
echo 'command failed: prints() { python -c $'\''\nfrom sys import argv\nfrom sys import stdout\nfrom re import sub\nu = lambda s: sub(r"\\\\x([0-9a-f]{1,2})", lambda m: "%c" % int(m.group(1), 16), s)\nfor a in argv[1:]:\n\tstdout.write(u(a))\n\tstdout.write("\\n")\n'\'' "$@"; }'

echo '$ prints a '\''\x0'\'' '\''\xff'\''|trie'
prints a '\x0' '\xff'|trie 2>&1 ||
echo 'command failed: prints a '\''\x0'\'' '\''\xff'\''|trie'

echo '$ prints xay '\''x\x0y'\'' '\''x\xffy'\''|trie'
prints xay 'x\x0y' 'x\xffy'|trie 2>&1 ||
echo 'command failed: prints xay '\''x\x0y'\'' '\''x\xffy'\''|trie'
)

